### ISSUE TITLE
Use of dnc

### ISSUE THREAD

**Issue by PaulDaoudi** [greydanus/dnc#4]
Hi, 
I am a student currently working on dnc, but I don't really understand how it works and especially how to use it.
I have looked into your example of the free-recall task, but I don't understand what input and what data you took (except for the flags). Can you explain it ?

Thank you.
Paul

**Comment by greydanus** [comment]
The DNC is like an RNN (eg a GRU or LSTM) and can be applied to the same problems as an RNN. The DNC is cool because it scales to larger memories far better than regular RNNs because it has a "long term" memory component whereas RNNs could be thought of as having only "short term" memory

see https://deepmind.com/blog/differentiable-neural-computers/

**Comment by PaulDaoudi** [comment]
Yes, but it is quite different from an LSTM classic no ? 
As I have understood the paper, the DNC is able to do two completely different tasks, whereas a classic neural network can only be trained for one.
For instance, DNC can find relations in a family tree and recognize the questions that we ask. I don't understand how this works since these two issues have nothing in common.

**Comment by greydanus** [comment]
Yeah, the architectures are both different. Here’s the thing that they don’t tell you in the paper: both DNC and LSTM are Turing-Complete, which means that _in theory_ they can both learn these tasks. The problem is that learning these tasks _in practice_ is really tough on LSTMs, but not so bad for the DNC. The reason the DNC works better, I think, is that it features a large structured long-term pool of differentiable memory

**Comment by PaulDaoudi** [comment]
Just to be sure, is it thanks to its large long term memory that he can be trained on two completely different tasks (constructing data and then answer questions about them using text) ?
I am sorry but I have some troubles figuring how it can do these tasks since a neural network can only be used for one specific task.
